name: "Prueba 04"

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  analyze_codeql:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    strategy:
      fail-fast: false
      matrix: 
        language: ['csharp'] 
        #language: ['csharp', 'c-cpp', 'javascript-typescript'] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Initializes the CodeQL tools for scanning.    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml
        debug: true
        
    #****************************************************************
    #La compilación debe hacerse despues del init y antes de analyze
    - name: Build
      run: |
        dotnet build ./csharp.sln
    #****************************************************************
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
          languages: ${{ matrix.language }}
          # Optional. Specify a category to distinguish between multiple analyses
          # for the same tool and ref. If you don't use `category` in your workflow,
          # GitHub will generate a default category name for you
          category: "my_category"
          #output: '../results'
    
    #- name: Display SARIF file
    #  run: cat ../results/csharp.sarif

#  upload_sarif:
#    name: Upload SARIF file
#    needs: analyze_codeql
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v4

#    - name: Upload SARIF file
#      uses: github/codeql-action/upload-sarif@v3
#      with:
#        sarif_file: '../results/csharp.sarif' 
#        category: "my_category"
    
