name: "Prueba 03"

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    strategy:
      fail-fast: false
      matrix: 
        language: ['csharp'] 
        #language: ['csharp', 'c-cpp', 'javascript-typescript'] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Initializes the CodeQL tools for scanning.    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml
        debug: true
        
    #****************************************************************
    #La compilación debe hacerse despues del init y antes de analyze
    - name: Build
      run: |
        dotnet build ./csharp.sln
    #****************************************************************
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
          languages: ${{ matrix.language }}
          # Optional. Specify a category to distinguish between multiple analyses
          # for the same tool and ref. If you don't use `category` in your workflow,
          # GitHub will generate a default category name for you
          category: "my_category"



    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        #upload: always
        #cleanup-level: brutal
        #add-snippets: false
        #skip-queries: false
        #upload-database: true
        wait-for-processing: true
        #expect-error: false
        sarif_file: '/home/runner/work/csharp/results/csharp.sarif'    
        category: 'upload-results-csharp'
    
