name: "Prueba 1"

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    strategy:
      fail-fast: false
      matrix: 
        language: ['csharp'] 
        #language: ['csharp', 'c-cpp', 'javascript-typescript'] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: |
        dotnet build ./csharp.sln
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
          languages: ${{ matrix.language }}
    
